import type { Metadata } from 'next';
import './globals.css';
import { poppins } from './fonts';
import { Footer, Navbar } from './components';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${poppins.className} antialiased flex flex-col min-h-screen`}>
				<Navbar />
				<main className='flex-grow'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
